// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObnCgfNJcxiV0Kcb4imnkB5kDQtgKVeI',
    appId: '1:807375253913:web:174f5a491fc59f34fce308',
    messagingSenderId: '807375253913',
    projectId: 'tugas-pam4',
    authDomain: 'tugas-pam4.firebaseapp.com',
    storageBucket: 'tugas-pam4.firebasestorage.app',
    measurementId: 'G-H2WD2Q23FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-JnblHAUJvKBF398KI8PN1Dvj_Pd4hs',
    appId: '1:807375253913:android:c0a86ce2ab5fe558fce308',
    messagingSenderId: '807375253913',
    projectId: 'tugas-pam4',
    storageBucket: 'tugas-pam4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI4SH3aTfcDgm3gtn-avyzoO71ZQcmj7g',
    appId: '1:807375253913:ios:cdf97110a13befb1fce308',
    messagingSenderId: '807375253913',
    projectId: 'tugas-pam4',
    storageBucket: 'tugas-pam4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI4SH3aTfcDgm3gtn-avyzoO71ZQcmj7g',
    appId: '1:807375253913:ios:cdf97110a13befb1fce308',
    messagingSenderId: '807375253913',
    projectId: 'tugas-pam4',
    storageBucket: 'tugas-pam4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBObnCgfNJcxiV0Kcb4imnkB5kDQtgKVeI',
    appId: '1:807375253913:web:acdcbc72a7c42baafce308',
    messagingSenderId: '807375253913',
    projectId: 'tugas-pam4',
    authDomain: 'tugas-pam4.firebaseapp.com',
    storageBucket: 'tugas-pam4.firebasestorage.app',
    measurementId: 'G-5CH95VEHRD',
  );
}
